version: "3"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - PROJECT_NAME=Task Management API
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
